all: 01_log/test_log 02_function/test_function 03_ft2/test_ft2 04_sleep/test_sleep

01_log/test_log:
	make -C "01_log"

02_function/test_function:
	make -C "02_function"

03_ft2/test_ft2:
	make -C "03_ft2"

04_sleep/test_sleep:
	make -C "04_sleep"

clean:
	make clean -C "./01_log"
	make clean -C "./02_function"
	make clean -C "./03_ft2"
	make clean -C "./04_sleep"